name: CI

on:
  pull_request:

jobs:
  lint:
    runs-on: docker
    container:
      image: ghcr.io/cachix/devenv/devenv:v1.11.1
      volumes:
        - /var/cache/forgejo-devenv:/home/devenv/.cache
    steps:
      - name: Probe
        shell: bash
        run: |
          echo "lint minimal probe"
          id
          pwd
          command -v devenv || true
