name: Hello

on:
  pull_request:

jobs:
  hello:
    runs-on: docker
    container:
      image: node:20-bookworm
    steps:
      - name: Echo
        shell: bash
        run: |
          echo "hello from $HOSTNAME"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          id
          pwd
